
services:
  keycloak_db:
    image: postgres:15-alpine
    container_name: keycloak_db
    command: 
      "postgres -c 'max_connections=500'"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${KC_DB}
      - POSTGRES_USER=${KC_DB_USER}
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
      - POSTGRES_HOST=${KC_DB_HOST}

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev 
    ports:
      - "8080:8080"
    volumes:
      - ../FriendsKCTheme:/opt/keycloak/themes/Friends
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_PASSWORD}
      - DB_DATABASE=${KC_DB}
      - KC_DB=${database}
      - KC_DB_URL_HOST=${KC_DB_HOST}
      - KC_DB_USERNAME=${KC_DB_USER}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    depends_on:
      - keycloak_db
    restart: always
volumes:
  postgres_data: {}
  keycloack_data: {}
