name: CI/CD Workflow for deploy themes keycloak

on: 
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Setup Pritunl Profile and Start VPN Connection
        uses: nathanielvarona/pritunl-client-github-action@v1
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
          profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.5
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_ODDS_CLOUD_KEY }}
            port: 22
            script: |
              cd ~/keycloak/KeycloakThemeJanitor
              git pull
              rm -rf ~/keycloak/KeycloakThemeJanitor/out
              /home/linuxbrew/.linuxbrew/bin/npm run build:jar
